[manifest]
id = "translation_ptbr"
version = "1.0.0"
display_name = "Brazilian Portuguese Translation"
description = "Brazilian Portuguese Translation of DK64. Includes custom font support for the language."
short_description = "Brazilian Portuguese Translation of DK64"
authors = [ "danilotec1-prog (localization and review)", "Ballaam (technical framework)", ]
game_id = "dk64"
minimum_recomp_version = "1.0.2"

[inputs]
elf_path = "build/mod.elf"
mod_filename = "translation_ptbr"
func_reference_syms_file = "Dk64Syms/dump.toml"
data_reference_syms_files = [ "Dk64Syms/data_dump.toml" ]
additional_files = ["thumb.dds"]
