// This file is autogenerated. See /font/joiner.py for the conversion file
typedef struct CharStruct {
	u16 x_start;
	u8 width;
} CharStruct;
#define FONT_6_WIDTH 256
#define FONT_6_HEIGHT 16
#define FONT_6_COUNT 3
#define FONT_1_WIDTH 72
#define FONT_1_HEIGHT 28
#define FONT_1_COUNT 18
